### ISSUE TITLE
[BUG] gifs are not played on linux

### ISSUE THREAD

**Issue by mohad12211** [frang75/nappgui_src#10]
https://user-images.githubusercontent.com/51754973/158998704-7f902b87-d582-4395-b90d-7d07c83aaac7.mp4

tested on linux mint and arch linux.
this is the binary that is downloaded here:https://nappgui.com/en/download/download.html
I also compiled the library on my system with gcc 11 and it has the same issue.

**Comment by frang75** [comment]
Hi @mohad12211!

Thank you very much for the feedback!

Animated GIF support for GTK3 was a bit tricky and, at the time, I didn't implement it because there were other more urgent things.  Thanks to your tests you have encouraged me to complete it. It's already working. The examples and source code have been updated.  

We keep in touch and thanks again.

**Comment by mohad12211** [comment]
Thank you for your efforts! I know how tricky and frustrating gtk can be, that what made me search for a replacement in the first place and found your great SDK, please keep it up!
I noticed some other bug, after your latest commit, the icons in the products demo is not rendering:
![image](https://user-images.githubusercontent.com/51754973/159188132-25645a34-9816-4a95-ba85-af5a8bd79501.png)
Terminal logs:
https://gist.github.com/mohad12211/ee27b6771f06fdf0a95b54c4fc15ba52

**Comment by frang75** [comment]
Yeah true! :blush:

Access to image information has changed for button and menu. Today I will upload the patch. 

Please don't hesitate to submit any issue, however small it may seem. The Linux version is the least I can test.  
The same for any functionality that is not implemented and may be useful to you.

See ya!

**Comment by frang75** [comment]
Solved!

**Comment by mohad12211** [comment]
Fantastic work!
