### ISSUE TITLE
Window default button function placement dependency

### ISSUE THREAD

**Issue by SamSandq** [frang75/nappgui_src#109]
In my code I had the following, where dialogue is an layout with an OK button:

```
    ...
    panel_layout(panel, dialogue);
    window_defbutton(w, ok);        //DOES NOT WORK!
    window_panel(w, panel);
    window_title(w, "Funtus");
    window_origin(w, pos);
    ...
```

The ok button does **not** show up as a default button. However, if I write

```
    ...
    panel_layout(panel, dialogue);
    window_panel(w, panel);
    window_defbutton(w, ok);        //WORKS!
    window_title(w, "Funtus");
    window_origin(w, pos);
    ...
```

it works fine.

So the placement does matter. If it isn't a bug, it should be documented.

**Comment by frang75** [comment]
Before `window_panel(w, panel);` your window is an empty container and `window_defbutton()` does nothing, because any button exists in the window. For this reason exists `window_defbutton()` and not `button_set_default()`. Really in both cases the SDK is working fine.

**Comment by SamSandq** [comment]
I accept that it is working, but... having made all the definitions before instantiating the window, it makes sense that the default button declaration/definition also would be taken into account when creating the window.

I believe a note to the effect that the call to `window_defbutton(...)` must be made after the window has been created should be added to the documentation.

**Comment by frang75** [comment]
Added a tip in function documentation: https://nappgui.com/en/gui/window.html#f28
