### ISSUE TITLE
Wrong cursor shape for ekGUI_CURSOR_SIZENS 

### ISSUE THREAD

**Issue by SamSandq** [frang75/nappgui_src#112]
Minor issue: the shape for `ekGUI_CURSOR_SIZENS` is just a resizing beam for down.

Please correct in `src/osgui/osx/osxglobals.m`, line 353:

from:
`nscursor = [[NSCursor resizeDownCursor] retain];`
to
`nscursor = [[NSCursor resizeUpDownCursor] retain];`

This may be just the Mac; I have not checked Windows or Linux.

**Comment by frang75** [comment]
Hi @SamSandq!
Fixed in this commit: https://github.com/frang75/nappgui_src/commit/5b247f67a1ac386ac75f2053c715010d9049f0e4

Thanks for reporting.
