### ISSUE TITLE
Selected item colour in listboxes and popups incorrect on Mac

### ISSUE THREAD

**Issue by SamSandq** [frang75/nappgui_src#115]
The selected item's colour is not according to Apple standard.

In `osglobals.m: i_theme_colors`, line 109, you have

`oscolor_NSColor_rgba_v([NSColor selectedControlColor], i_SELBG_COLOR);`

which shows up, in a listbox, like this:

![Screenshot 2024-03-18 at 14 48 11](https://github.com/frang75/nappgui_src/assets/50418806/54ac1168-7965-4cf7-8547-1c2a64fd1ad4)

Instead, the line should read:

`oscolor_NSColor_rgba_v([NSColor selectedContentBackgroundColor], i_SELBG_COLOR);`

which shows the Mac standard colour:

![Screenshot 2024-03-18 at 14 47 14](https://github.com/frang75/nappgui_src/assets/50418806/059b00f8-a84a-4137-9226-b2ff6c656bd2)

This makes the highlighted / selected lines in popups and listboxes follow all other applications on the Mac. It also applies to tableviews, where it may not be wanted. I suggest making these user-configurable to cater for all needs.

**Comment by SamSandq** [comment]
I made a slight mistake above: popups are standard mac controls, and use the correct colour, like combo boxes too. The listbox and tables are NAppGUI implementations, and sometimes do not follow standard usage (at least on the Mac)

**Comment by frang75** [comment]
You're right. From macOS Mojave, Apple provide a more convenient selection color . Fixed here https://github.com/frang75/nappgui_src/commit/7485964f68e5647c5a31e267ce3a8d2b059ca031
