### ISSUE TITLE
CMake throws up on Windows

### ISSUE THREAD

**Issue by alex-s168** [frang75/nappgui_src#118]
It complains about there begin backslashes in line 40 in cmake_install.cmake
I fixed it by removing like 16 from NAppGenerateTools.cmake

**Comment by frang75** [comment]
Hi @alex-s168 
Please provide more context. Version of Windows, version of Visual Studio, version of CMake and logs.

**Comment by frang75** [comment]
Fixed in this commit: https://github.com/frang75/nappgui_src/commit/cda8a3fccf101ecae03a383fd481517518d70075
