### ISSUE TITLE
The main site is broken

### ISSUE THREAD

**Issue by Starpelly** [frang75/nappgui_src#122]
This page -> https://nappgui.com/, doesn't load.

**Comment by eriklins** [comment]
Loads fine from here (Germany), so might just be a temporary issue.

**Comment by SamSandq** [comment]
No problems from Finland either...

**Comment by frang75** [comment]
Hi! I close this issue, because there are not problems with the website. Perhaps a temporal server issue.

**Comment by Starpelly** [comment]
I should've clarified I'm trying to connect from Indianapolis, Indiana.
