### ISSUE TITLE
Allow building for Windows with MinGW-w64/GCC

### ISSUE THREAD

**Issue by brechtsanders** [frang75/nappgui_src#125]
Your website says building for Windows requires Visual Studio.

I have just succeeded doing a native Windows build with MinGW-w64 and GCC (from https://winlibs.com/).

Note however that some changes were needed to accomplish this.

My recipe is published here:

https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/nappgui.winlib

Feel free to incorporate these changes as needed to support Windows without Microsoft tools.

**Comment by frang75** [comment]
Hi @brechtsanders!
Yes, the MicGW still is not supported by NAppGUI. 
Thanks for reporting.

**Comment by frang75** [comment]
The support for MinGW has been added in NAppGUI 1.4.2.
Doc: https://nappgui.com/en/guide/win_mac_linux.html#h4
Commit: https://github.com/frang75/nappgui_src/commit/5f638074231f028a5eb8a07c2f0d232edad408c6
