### ISSUE TITLE
Needs support for Linux aarch64 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by g8kig** [frang75/nappgui_src#13]
Running 64bit on the Raspberry Pi 4, for example.

**Comment by frang75** [comment]
Hi @g8kig!

Thank you very much for your feedback.  
ARM-Linux versions of NAppGUI are tested on Raspbian 8, 9, 10 all 32-bit. I see that a 64-bit Raspberry Pi OS is already available, so I will include support for 64-bit ARM soon.

Keep in touch!

![raspian_10_buster_32bits](https://user-images.githubusercontent.com/42999199/162811512-6a24b598-9fa9-4c49-b77b-74b05581cc30.png)
