### ISSUE TITLE
Crash in ColorView - NULL pointer access

### ISSUE THREAD

**Issue by MahmoudFayed** [frang75/nappgui_src#131]
Hello

This is a great project, Thanks for sharing. 
Also, the documentation and samples are amazing.

Today, I tried to build the library from source code (Windows 11, VS 2022)

When I run nappgui_src\build\Debug\bin\colorview.exe and click on any color
I get the message (NULL pointer access)
File: oscontrol.cpp
Line: 470

Greetings,
Mahmoud

**Comment by frang75** [comment]
Hi @MahmoudFayed!

The crash has been fixed in this commit: https://github.com/frang75/nappgui_src/commit/761ce9ab81a33f74f7591609f02508d5da2c1dc7

Thanks for report and welcome to NAppGUI.

**Comment by MahmoudFayed** [comment]
Thank you very much
