### ISSUE TITLE
Warnings aplenty with gcc

### ISSUE THREAD

**Issue by Kharzette** [frang75/nappgui_src#137]
Am I the only one getting loads of these warnings?

`nappgui_src/src/core/arrst.hxx:180:19: warning: inline function ‘arrst_bool_t_end’ declared but never defined
  180 |     __INLINE void arrst_##type##_end(void)
      |                   ^~~~~~
nappgui_src/src/core/core.hxx:309:5: note: in expansion of macro ‘ArrStFuncs’
  309 |     ArrStFuncs(type); \
      |     ^~~~~~~~~~
nappgui_src/src/core/core.hxx:318:1: note: in expansion of macro ‘DeclSt’
  318 | DeclSt(bool_t);
      | ^~~~~~`

I'm using -std=gnu2x with gcc 13.2.1

I was going to just disable the warnings and keep going but I ran across a bug in gcc that seemed to indicate there was no way to disable that warning.  I'm guessing this gcc bug was never fixed.

Macros are really confusing to me so I don't have a clue what any of that is doing.

My best plain english guess of what the warning is trying to say is that these inline functions are declared here but nobody ever calls them?  I get this on including nappgui.h and the same batch again for osmain.h.

**Comment by frang75** [comment]
Hi @Kharzette
Please report the exact commands you are using to compile.

Meanwhile, you can use the NAppGUI build system as indicated in Quick Start Guide 
https://nappgui.com/en/start/quick.html#h3
```
git clone --depth 1 https://github.com/frang75/nappgui_src.git
cd nappgui_src
cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build -j 4
```

**Comment by Kharzette** [comment]
My earlier comment was very unclear, sorry about that!

The overall source compiles just fine.  This is my own code that just links against the built nappgui libs (core draw2d etc).

Really what I should do is just pull out and build a sample and see if the same warnings happen.  I'll try that later and report back.  Thanks!

**Comment by Kharzette** [comment]
Experimented a bit more on this.  Grabbed the simple demo/hello/main.c and put it in the same dir as my app and compiled it with gcc -c and -I for the nappgui include dirs.

I tried all of the -std options that determine which c language version the compiler uses.  All options past 90 give the warnings, so if you do like -std=gnu90 you get no warnings.

That should give me a few hints to go and read about the differences between gnu90 and the others.

**Comment by frang75** [comment]
Thanks for the info. I'll test compilation with modern C/C++ standards in gcc 13.

**Comment by Kharzette** [comment]
Sorry I didn't look at this for a few days, about an hour after I wrote the above comment I found myself on a hospital bed 😆   All is well now though.

So it looks like what gcc is unhappy about is the functions have no body.  If I just put a {} at the end of all of the _end functions, the warnings go away.  These are at the very bottom of arrpt.hxx, arrst.hxx, setpt.hxx, and setst.hxx.

Were those functions supposed to be doing something though?

**Comment by frang75** [comment]
Hello! I hope you are well. 
Macros for runtime type checking are defined in `arrpt.hxx` (and others). They are activated by `DeclSt(type)`/`DeclPt(type)`. I will test the compilation with different language standards to avoid warnings.

**Comment by frang75** [comment]
Fixed warnings in this commit: https://github.com/frang75/nappgui_src/commit/86265ffe3c7c933d09b179d431d0025ec2985ddc

**Comment by Kharzette** [comment]
Wonderful thanks!  Tested and no warnings, everything working well
