### ISSUE TITLE
Build on Ubuntu not displaying WebView component

### ISSUE THREAD

**Issue by d33p-dev** [frang75/nappgui_src#142]
Hi @frang75 !  I built and ran the sample, WebHello, on Ubuntu but couldn't get the webView component to display in the app.  The app runs/builds fine, no errors logged to console but the actual webView component will not render.  I can't yet debug on Ubuntu but I will soon and try to isolate what the problem is but I wanted to bring it to your attention.

I am using/running/customizing the WebView component on MacOS which works great.  As you know, I had the ARM build for Windows giving me some headaches so I haven't tested yet Windows build for WebView but I'll spin up an X64 VM soon and build the Windows webView sample there and test as my next step.

Thanks and lmk what I'm missing in my setup to get WV working on Ubuntu/Linux.  I sent some discord messages that might shed some light on the issue possibly.

**Comment by frang75** [comment]
Hi @d33p-dev 
In Linux/Ubuntu is necessary to install the webview-gtk development libraries.

https://nappgui.com/en/gui/webview.html#h1.3

**Comment by d33p-dev** [comment]
LOL so RTFM..........................  THANKS!!!!!!!
