### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by alex-s168** [frang75/nappgui_src#149]
The documentation for resource packs uses `respack_image`, which does not exist.

**Comment by frang75** [comment]
Hi @alex-s168.
Yes it's true. The examples in this page are out of date. `respack_image()` was changed by `image_from_resource()`. I will update in next documentation build.
Thanks for reporting.

**Comment by frang75** [comment]
@alex-s168 

Fixed: https://nappgui.com/docs/r5452/en/guide/resources.html#h6
