### ISSUE TITLE
errors when using clangd

### ISSUE THREAD

**Issue by alex-s168** [frang75/nappgui_src#150]
I am using clangd (18) which is a language server for C and C++.
I get following error in included nappgui headers: `At least gcc 4.2 is required`.
This is probably a bug

**Comment by alex-s168** [comment]
> Hi @alex-s168.
> Its not a bug, its a safeguard. The lower GCC version used "officially" in NAppGUI CI is 4.6.3 (Ubuntu12) and 4.3 (MacOSX Snow Leopard). Previous versions cannot be guaranteed to work.
> With Clang, the lowest version used is 3.0.0 (Ubuntu12).
> 
> More info here 
> https://nappgui.com/en/guide/win_mac_linux.html
> 

I get that but I am using clangd 18. It looks like it doesn't set the preprocessor defines

**Comment by frang75** [comment]
Check that you really have Clang selected with CMake:
`-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++`

More info here 
https://nappgui.com/en/guide/win_mac_linux.html#h8
