### ISSUE TITLE
How set "target_link_libraries"

### ISSUE THREAD

**Issue by kkstun** [frang75/nappgui_src#162]
Target "napphello" links to:

    nappgui::osapp

  but the target was not found.

**Comment by frang75** [comment]
Hi @kkstun 
I would need some more context to really know what is going on. In general:
* You must compile and install NAppGUI using these instructions:
https://nappgui.com/en/guide/build.html

* To create a new application, I recommend you follow these steps:
https://nappgui.com/en/guide/newprj.html#h1

* However, if you want to create your own `CMakeLists.txt` from scratch without using NAppGUI commands, you should use:
```
...
find_package(nappgui REQUIRED)
...
target_link_libraries(napphello ${NAPPGUI_LIBRARIES})
```

![nappgui_hello](https://github.com/user-attachments/assets/3b4cbd39-08b5-49bf-94b9-8e1e5fc73f17)

**Comment by kkstun** [comment]
Thanks. 
I forgot this step：
cmake --install build --config Release --prefix C:/nappgui
