### ISSUE TITLE
Build errors with CMake >= 3.21.2

### ISSUE THREAD

**Issue by TheMartianObserver** [frang75/nappgui_src#2]
Hello! I'm excited to try this library out, but can't get the demos to build on my macOS system.

I followed the macOS quick start instructions [here](https://github.com/frang75/nappgui_src#quick-start-in-macos). First, I get the CMake output as shown in [this gist](https://gist.github.com/TheMartianObserver/715c9fab4b6d4ccf8e21a77d5b81bc5b). Looks fine aside from the upfront warning about the CMake version (I'm using the latest 3.21.2).

Then, running `xcodebuild`, I get the output in [this other gist](https://gist.github.com/TheMartianObserver/2e7d2f7ccd980ec95ade741f35f6fe6c), with the first error shown on [line 615](https://gist.github.com/TheMartianObserver/2e7d2f7ccd980ec95ade741f35f6fe6c#file-gistfile1-txt-L615).

Error seems to emanate from draw2d_osx.ixx.

Unfortunately, I'm not much of a macOS developer, so I'm not sure how one would even go about correcting this! (I guess I need to learn 😄)

Thanks for any help on this!

**Comment by frang75** [comment]
Hi, it's true. I had the same error with CMake 3.21.2. It seems something wrong in new CMake when detecting Cocoa Framework. Please download the previous CMake package (3.20.5) and repeat the process. Delete your `nappgui_build` directory and create it again.

I will investigate if it is a CMake bug or if instead I have to modify the scripts for macOS.

Thank you very much for the report :-)

**Comment by TheMartianObserver** [comment]
Great! Using the previous version of CMake fixes the build issues. Now to play with the library!

**Comment by frang75** [comment]
From [here](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5926), newer versions of CMake treat the `*.ixx` extension as source code files (not headers) due to C++ 20 modules. NAppGUI uses this extension for the declaration of internal types, so there is a conflict with CMake. In future revisions, NAppGUI should change this extension and not use it as headers.

**Comment by frang75** [comment]
[NAP-5]

**Comment by frang75** [comment]
Solved!
