### ISSUE TITLE
right Shift + Tab doesnt move focus to previous control

### ISSUE THREAD

**Issue by 4silvertooth** [frang75/nappgui_src#20]
Tested on windows 10,
If I press the `left side Shift` + `Tab` the focus does move to previous control but shouldn't `right side shift` + `Tab` mimic the same, right now it's just moving to next element like as if right shift isn't pressed at all.

**Comment by frang75** [comment]
Hi @4silvertooth! Thank you very much for the feedback

True, the Right-Shift key was not enabled in Windows to switch to the previous tabstop. I have uploaded a patch that fixes it. On macOS and Linux Right-Shift works fine.

**Comment by 4silvertooth** [comment]
Yupp, works now.
