### ISSUE TITLE
#include "res_assert.h"

### ISSUE THREAD

**Issue by evilteach** [frang75/nappgui_src#21]
Where is the  source for res_assert.h that is found in gui.cpp?

**Comment by frang75** [comment]
The files `res_assert.c` and `res_assert.h` are automatically generated at build time by nrc (NAppGUI Resource Compiler) when running the CMake script. I attach them here, but they are considered "generated code"and not "source code".

More info:
https://nappgui.com/en/start/resources.html#h7
https://nappgui.com/en/start/quick.html

[res_assert.zip](https://github.com/frang75/nappgui_src/files/9368050/res_assert.zip)

**Comment by evilteach** [comment]
Ah.  So they get cleaned up by the cmake.
Thank you.
