### ISSUE TITLE
How to working with the third-party static library(Ex: libusb-1.0.lib) 

### ISSUE THREAD

**Issue by rick-hanpin** [frang75/nappgui_src#25]
Hello Frang:
I'm new to NAppGUI and CMake. about below question I can't find any answer on Google.  
When add new project by command "desktopApp("TestUSB" "Ben/TestUSB" "" NRC_NONE)", and add the "target_link_libraries(TestUSB usb-1.0)" to CMakeLists.txt file on my new project folder , but this file will be updated automatic every time when CMake configure.
How does the best way the NAppGUI working with a third-party library (Example; libusb-1.0.lib libusb-1.0.a ), if I don't want re-compiler the third-party library source code?

**Comment by frang75** [comment]
Hi @rick-hanpin, thank you for use NAppGUI!

You can link to the external library within the main `CMakeLists.txt` (`/src/CMakeLists.txt`). Indeed, the `CMakeLists.txt` in the subfolders are temporary and will be rewritten.

```
if(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
    target_link_libraries(TestUSB PRIVATE "/library/windows_folder/libusb-1.0.lib")
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    target_link_libraries(TestUSB PRIVATE "/library/linux_folder/libusb-1.0.a")
endif()
```

**Comment by rick-hanpin** [comment]
Hi @frang75 
Thank you for taking the time to reply, I implemented it according to your suggestion, and the result has been successful.

**Comment by NejatHakan** [comment]
Hi Francisco,

**VSCode hints 2 error messages concerning 2 lines in src/CMakeLists.txt**

1. CMake Error at CMakeLists.txt:42 (target_include_directories):Cannot specify include directories for target "MyNewApp" which is not built by this project.
2. CMake Error at CMakeLists.txt:43 (target_link_libraries):Cannot specify link libraries for target "MyNewApp" which is not built by this project.

**These are the lines (copy&paste from src/CMakeLists.txt)**
\# Your projects here!
desktopApp("MyNewApp" "myapp" "osapp;inet" NRC_PACKED)
target_include_directories("MyNewApp" PUBLIC "/usr/include/mariadb")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libmariadb.a")

Please take also a closer look in the screenshot if you want to take look into my VSCode Project structure.

![vscode_cmake_error_hint](https://user-images.githubusercontent.com/8217587/221192102-02e835a0-c9f3-4d92-a0d5-9a99c715096d.png)

**Comment by M0JXD** [comment]
Hi, NAppGUI's CMake build seems to have changed a bit since when this issue was opened with a lot of stuff hidden in the provided functions like nap_project_desktop_app. 

Is there a particular way that's recommended? E.g. I'm trying to make a project with PortAudio as a third-party lib and this is what I have so far (not tested beyond building the NAppGUI demo with it linked as I'm just starting this project):

```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0079 NEW)
project(project_name)
find_package(nappgui REQUIRED)
find_package(portaudio REQUIRED)
include("${NAPPGUI_ROOT_PATH}/prj/NAppProject.cmake")
include("${NAPPGUI_ROOT_PATH}/prj/NAppCompilers.cmake")
nap_config_compiler()
nap_project_desktop_app(project_name project_name)
target_link_libraries(project_name portaudio_static)
```

Thanks

**Comment by M0JXD** [comment]
Hi @frang75 :)

Yes, I have both installed system wide (hence the policy is required). I added some PortAudio code into the main file of the NAppGUI app to test and it builds fine, so it's linking OK.

I was just worried there was something I was missing/wrong. I'm not very comfortable with CMake and the 'nap' macros seem to abstract a lot of boilerplate, so I was worried trying to link an external library to the project might conflict with what's happening in them, or there might be a better way, but all seems good!

Is there any intention for NAppGUI to wrap native system access to audio and peripherals (USB, Camera etc.)?

Thanks for your great work and help.

**Comment by frang75** [comment]
> Is there any intention for NAppGUI to wrap native system access to audio and peripherals (USB, Camera etc.)?

This is outside the scope of the project. But it could be included as an optional library within NAppGUI if there is a real demand for this feature.
