### ISSUE TITLE
Hi how Capture the "Return" key pressed event on edit box

### ISSUE THREAD

**Issue by lbhack** [frang75/nappgui_src#31]

**Comment by frang75** [comment]
Hi @lbhack,

At this time, it is not possible to capture the `[RETURN]` key press in the `Edit` control. Using `edit_OnChange()` you can control changes to the string while it is being written, but NOT the Return.

On the other hand, this doesn't make much sense either. A common thing is to detect that `[RETURN]` has been pressed to "accept" a dialog box and close the window. This can be done:

1) Use the `ekWINDOW_RETURN` constant in `window_create()` to allow a window to accept the `[RETURN]` key. The default behavior will be to close the window.

2) If you want to prevent the window from closing or do something when pressing `[RETURN]`, you must use the `window_OnClose()` event and decide there whether to close the window or not. See `EvWinClose` event data and its `gui_close_t` value.

More info about that here:
https://nappgui.com/en/gui/window.html#h2

A demo to create windows that close with RETURN or ESC:
https://nappgui.com/en/howto/guihello.html#h10

**Comment by frang75** [comment]
Please read the link I gave you earlier. To avoid closing the window, you must set `event_result()` to `FALSE`.

More info about that here:
https://nappgui.com/en/gui/window.html#h2
