### ISSUE TITLE
Error Report - Assertion failure in clock.c

### ISSUE THREAD

**Issue by lbhack** [frang75/nappgui_src#32]
<img width="421" alt="error_show_in 2_minutes_run_the program" src="https://user-images.githubusercontent.com/2568488/213299087-eccf7767-f8fa-4c5b-a3a0-b18b6b4b02bc.png">
hi i am getting this after a while i execute my program !!!!

**Comment by frang75** [comment]
I need more context, please.

Do your application starts with?
```
#include "osmain.h"
osmain(i_create, i_destroy, "", App)
```

or?

```
#include "osmain.h"
osmain_sync(.04, i_create, i_destroy, i_update, "", App)
```

**Comment by lbhack** [comment]
/*
 Author josesaleh
 MIT License
 2022=2023
 */
#include "nappgui.h"
#include "inet.h"
#include "httpreq.h"
#include "json.h"



typedef struct _app_t App;



struct _app_t
{
    Window *window;
    TextView *text;
    Layout *lay;
    Label *la;
    char_t *str;
    bool_t on;
    uint32_t i;
    Thread *th;
    Button *abt;
};


/*---------------------------------------------------------------------------*/

/*
The function get_ip is responsible for making an HTTP GET request to the api.ipify.org website to retrieve the public IP address of the device. It creates an instance of the Http struct using the http_secure function, passing in the hostname and port as arguments. It then makes an HTTP GET request to the root path ("/") and checks if the request was successful by checking the return value of the http_get function. If successful, it creates a memory stream and reads the response body into it. The function then reads the stream line by line using the stm_lines function, and formats the IP address in a string which is then stored in app->str
*/
static void get_ip(App *app)
{
    
    Http *http = http_secure("api.ipify.org", 443);
    Stream *stm = NULL;
    

    if (http_get(http, "/", NULL, 0, NULL) == TRUE)
    {
        uint32_t status = http_response_status(http);
        if (status >= 200 && status <= 299)
        {
            stm = stm_memory(4096);
            if (http_response_body(http, stm, NULL) == FALSE)
                stm_close(&stm);
        }
    }
    
    http_destroy(&http);
    stm_lines(line, stm);
    app->str = tc(str_printf("NET IP : %s",line));
    stm_next(line, stm);
    
}

/*---------------------------------------------------------------------------*/
/*
 The function i_on is called repeatedly as long as app->on is TRUE. It prints the current character of app->str at index app->i to the text view using the textview_printf function. If the current index app->i is equal to the length of app->str, it sets app->on to FALSE, app->i to 0, and enables the refresh button using the cell_enabled function.
 */
static void i_on(App *app)
{
    
    
    if (app->on == TRUE)
    {
        
        textview_printf(app->text,"%c",app->str[app->i++]);
        if(app->i == str_len_c(app->str))
        {
            app->on = FALSE;
            app->i = 0;
            cell_enabled(app->abt, TRUE);
            
        }
        //i = i+1;
    }
    
}
/*
 The function inits is called by the runme function, it clears the text view using the textview_clear function and calls the get_ip function to retrieve the IP address and sets app->on to TRUE.
 */
static void inits(App *app)
{
    textview_clear(app->text);
    get_ip(app);
    app->on = TRUE;
}
/*
The function runme is called when the "REFRESH IP" button is pressed. It disables the refresh button using the cell_enabled function and creates a new thread that calls the inits function using the bthread_create function.
 */
static void runme(App *app)
{
    cell_enabled(app->abt, FALSE);
    app->th = bthread_create(inits, app, App);
    bthread_close(&app->th);
}
static void i_OnClose(App *app, Event *e)
{
    osapp_finish();
    unref(app);
    unref(e);
}

static Panel *i_panel(App *app)
{
    Panel *panel = panel_create();
    Layout *layout = layout_create(1, 3);
    Button *button = button_push();
    Button *Exit_bt = button_push();
    TextView *text = textview_create();
    app->text = text;
    app->lay = layout;
    button_text(button, "REFRESH IP");
    button_text(Exit_bt, "Exit");
    textview_color(app->text, kCOLOR_GREEN);
    textview_halign(app->text,ekCENTER);
    button_OnClick(button, listener(app,runme, App));
    button_OnClick(Exit_bt, listener(app,i_OnClose, App));
    layout_button(layout, Exit_bt, 0, 2);
    layout_button(layout, button, 0, 1);
    layout_textview(layout, text, 0, 0);
    layout_hsize(layout, 0, 250);
    layout_vsize(layout, 2, 100);
    layout_vsize(layout, 0, 20);
    layout_margin(layout, 5);
    layout_vmargin(layout, 0, 5);
    layout_vmargin(layout, 1, 5);
    app->abt = layout_cell(layout, 0, 1);
    panel_layout(panel, layout);
    
    return panel;
}

/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/

static App *i_create(void)
{
    App *app = heap_new0(App);
    Panel *panel = i_panel(app);
    app->window = window_create(ekWINDOW_TITLE);
    window_panel(app->window, panel);
    window_title(app->window, "IP INFO");
    window_origin(app->window, v2df(500, 200));
    window_OnClose(app->window, listener(app, i_OnClose, App));
    window_show(app->window);
    app->on = FALSE;
    return app;
}

/*---------------------------------------------------------------------------*/

static void i_destroy(App **app)
{
    window_destroy(&(*app)->window);
    heap_delete(app, App);
}

/*---------------------------------------------------------------------------*/

#include "osmain.h"
osmain_sync(0.02,i_create, i_destroy,i_on,NULL, App)

**Comment by lbhack** [comment]
/*
 Author josesaleh
 MIT License
 2022=2023
 */
#include "nappgui.h"
#include "inet.h"
#include "httpreq.h"
#include "json.h"



typedef struct _app_t App;



struct _app_t
{
    Window *window;
    TextView *text;
    Layout *lay;
    Label *la;
    char_t *str;
    bool_t on;
    uint32_t i;
    Thread *th;
    Button *abt;
};


/*---------------------------------------------------------------------------*/

/*
The function get_ip is responsible for making an HTTP GET request to the api.ipify.org website to retrieve the public IP address of the device. It creates an instance of the Http struct using the http_secure function, passing in the hostname and port as arguments. It then makes an HTTP GET request to the root path ("/") and checks if the request was successful by checking the return value of the http_get function. If successful, it creates a memory stream and reads the response body into it. The function then reads the stream line by line using the stm_lines function, and formats the IP address in a string which is then stored in app->str
*/
static void get_ip(App *app)
{
    
    Http *http = http_secure("api.ipify.org", 443);
    Stream *stm = NULL;
    

    if (http_get(http, "/", NULL, 0, NULL) == TRUE)
    {
        uint32_t status = http_response_status(http);
        if (status >= 200 && status <= 299)
        {
            stm = stm_memory(4096);
            if (http_response_body(http, stm, NULL) == FALSE)
                stm_close(&stm);
        }
    }
    
    http_destroy(&http);
    stm_lines(line, stm);
    app->str = tc(str_printf("NET IP : %s",line));
    stm_next(line, stm);
    
}

/*---------------------------------------------------------------------------*/
/*
 The function i_on is called repeatedly as long as app->on is TRUE. It prints the current character of app->str at index app->i to the text view using the textview_printf function. If the current index app->i is equal to the length of app->str, it sets app->on to FALSE, app->i to 0, and enables the refresh button using the cell_enabled function.
 */
static void i_on(App *app)
{
    
    
    if (app->on == TRUE)
    {
        
        textview_printf(app->text,"%c",app->str[app->i++]);
        if(app->i == str_len_c(app->str))
        {
            app->on = FALSE;
            app->i = 0;
            cell_enabled(app->abt, TRUE);
            
        }
        //i = i+1;
    }
    
}
/*
 The function inits is called by the runme function, it clears the text view using the textview_clear function and calls the get_ip function to retrieve the IP address and sets app->on to TRUE.
 */
static void inits(App *app)
{
    textview_clear(app->text);
    get_ip(app);
    app->on = TRUE;
}
/*
The function runme is called when the "REFRESH IP" button is pressed. It disables the refresh button using the cell_enabled function and creates a new thread that calls the inits function using the bthread_create function.
 */
static void runme(App *app)
{
    cell_enabled(app->abt, FALSE);
    app->th = bthread_create(inits, app, App);
    bthread_close(&app->th);
}
static void i_OnClose(App *app, Event *e)
{
    osapp_finish();
    unref(app);
    unref(e);
}

static Panel *i_panel(App *app)
{
    Panel *panel = panel_create();
    Layout *layout = layout_create(1, 3);
    Button *button = button_push();
    Button *Exit_bt = button_push();
    TextView *text = textview_create();
    app->text = text;
    app->lay = layout;
    button_text(button, "REFRESH IP");
    button_text(Exit_bt, "Exit");
    textview_color(app->text, kCOLOR_GREEN);
    textview_halign(app->text,ekCENTER);
    button_OnClick(button, listener(app,runme, App));
    button_OnClick(Exit_bt, listener(app,i_OnClose, App));
    layout_button(layout, Exit_bt, 0, 2);
    layout_button(layout, button, 0, 1);
    layout_textview(layout, text, 0, 0);
    layout_hsize(layout, 0, 250);
    layout_vsize(layout, 2, 100);
    layout_vsize(layout, 0, 20);
    layout_margin(layout, 5);
    layout_vmargin(layout, 0, 5);
    layout_vmargin(layout, 1, 5);
    app->abt = layout_cell(layout, 0, 1);
    panel_layout(panel, layout);
    
    return panel;
}

/*---------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------*/

static App *i_create(void)
{
    App *app = heap_new0(App);
    Panel *panel = i_panel(app);
    app->window = window_create(ekWINDOW_TITLE);
    window_panel(app->window, panel);
    window_title(app->window, "IP INFO");
    window_origin(app->window, v2df(500, 200));
    window_OnClose(app->window, listener(app, i_OnClose, App));
    window_show(app->window);
    app->on = FALSE;
    return app;
}

/*---------------------------------------------------------------------------*/

static void i_destroy(App **app)
{
    window_destroy(&(*app)->window);
    heap_delete(app, App);
}

/*---------------------------------------------------------------------------*/

#include "osmain.h"
osmain_sync(0.02,i_create, i_destroy,i_on,NULL, App)

**Comment by lbhack** [comment]
<img width="263" alt="ip_linux" src="https://user-images.githubusercontent.com/2568488/213375727-a64ded12-b378-4f29-8e35-1042c4f70463.png">

**Comment by lbhack** [comment]
<img width="263" alt="ip_linux" src="https://user-images.githubusercontent.com/2568488/213375815-6c4390fc-1204-4b3b-8dec-bfe3eecc91ea.png">
<img width="260" alt="ip_mac" src="https://user-images.githubusercontent.com/2568488/213375824-51067c80-bb11-4c51-92fe-93180cd5d4bf.png">
<img width="260" alt="ip_mac" src="https://user-images.githubusercontent.com/2568488/213375856-0134bef5-8c1b-4fe5-b583-4c306b1c957a.png">

**Comment by lbhack** [comment]
<img width="263" alt="ip_linux" src="https://user-images.githubusercontent.com/2568488/213375945-67bb8391-2531-446e-8323-102c396be31f.png">
<img width="260" alt="ip_mac" src="https://user-images.githubusercontent.com/2568488/213375958-a9d555b6-ea4f-4143-9250-bda03438ae7e.png">
<img width="264" alt="ip_win" src="https://user-images.githubusercontent.com/2568488/213375973-63f25e6a-d1ae-47ef-bb96-efd74db04d74.png">

**Comment by frang75** [comment]
Hi @lbhack 

This assertion reveals that something is wrong with the synchronous application. The current timestamp is "after" the previous timestamp. This can happen if the time inside `i_on()` is greater than the 50 frames/second (0.02) refresh rate. I have not been able to reproduce it. If it continues, try changing `0.02` to `0.04` and test.

On the other hand, the application contains several anomalies that you should correct before continuing:
- Numerous warnings.
- Memory leaks. `str_printf()` generates dynamic memory that you must free with str_destroy().
- You are calling gui text_view functions from a secondary thread. Please review.
https://nappgui.com/en/osapp/osapp.html#h3
- `runme() `doesn't make any sense. You create a secondary thread only to modify a GUI element (something forbidden) GUI elements are ONLY accessed from the main thread. Secondary threads are for performing NO GUI actions.

![Screenshot 2023-01-19 at 18 15 35](https://user-images.githubusercontent.com/42999199/213521094-db1abae5-7812-4030-b9ee-c0c0260abea1.png)

**Comment by lbhack** [comment]
hi @frang75 thanks for your answer I fix it all the warnings and remove it the thread .
