### ISSUE TITLE
How to animate text in a TextView control

### ISSUE THREAD

**Issue by lbhack** [frang75/nappgui_src#34]
hi i am getting issues when i remove the bthread_sleep the uptime in os_task is not effect to delay the update function is my issue or is api issues thanks this is my code .

static uint32_t i_m(App *app)
{
//    uint32_t c;
//    real32_t ipf;
//
//    for(c=0;c <= 100;c++)
//    {
//        bthread_sleep(5);
//        app->i = c;
//        for (ipf = .0f; ipf <= .99f; ipf += .1f) {
//            // code here
//            bthread_sleep(5);
//            app->pos = ipf;
//
//        }
//    }
    for(app->i=0;app->i <= str_len_c(app->str->data);app->i++)
    {
        bthread_sleep(100);
    }
    
    
   return (uint32_t)app->i;
    
    
}

static void i_on(App *app)
{
    
//    progress_value(app->spr,app->pos);
//    textview_printf(app->text,"update : %d\n",app->i);
//    textview_scroll_down(app->text);
       if (app->on == TRUE)
       {
           
           textview_printf(app->text,"%c",app->str->data[app->i]);
           if (app->i == str_len_c(app->str->data))
           {
               app->on = FALSE;
               app->i = 0;
               
               
           }
     }
    
        
   
    
}

static void i_end(App *app,const uint32_t rvalue)
{
    
    if (rvalue == str_len_c(app->str->data)) {
        textview_printf(app->text,"Task completed successfully\n");
    }
    else {
            textview_printf(app->text,"Task failed with error code %d\n", rvalue);
        }
           
       
            
   
}
/*
 The function inits is called by the runme function, it clears the text view using the textview_clear function and calls the get_ip function to retrieve the IP address and sets app->on to TRUE.
 */
static void inits(App *app,Event *e)
{
    
    //cell_enabled(app->abt, FALSE);
    app->on = TRUE;
    get_ip(app);
    osapp_task(app,.04,i_m,i_on,i_end, App);
    unref(e);
    
}

**Comment by frang75** [comment]
What are you really trying to do? If what you want is to animate a text inside a TextView, you are facing a synchronous application case.

A synchronous application is one that has to update its state at regular intervals whether or not the user interacts (like a video game).

In that case you just have to use `osmain_sync` to start the application and update the state of the TextView inside the i_update() method (like in a video game).

No need to create additional threads or tasks.

More info about synchronous application
https://nappgui.com/en/osapp/osapp.html#h2

An example of synchronous application (easy game):
https://nappgui.com/en/demo/bricks.html

An example of text animation:

```
/* NAppGUI Hello World */

#include "nappgui.h"

typedef struct _app_t App;

struct _app_t
{
    Window *window;
    TextView *text;
    uint32_t anim_frame; 
};

/*---------------------------------------------------------------------------*/

static void i_OnButton(App *app, Event *e)
{
    /* Animation is not running */
    if (app->anim_frame == UINT32_MAX)
    {
        /* Start animation */
        app->anim_frame = 0;
    }

    unref(e);
}

/*---------------------------------------------------------------------------*/

static Panel *i_panel(App *app)
{
    Panel *panel = panel_create();
    Layout *layout = layout_create(1, 3);
    Label *label = label_create();
    Button *button = button_push();
    TextView *text = textview_create();
    app->text = text;
    label_text(label, "Hello!, I'm a label");
    button_text(button, "Start Animation");
    button_OnClick(button, listener(app, i_OnButton, App));
    layout_label(layout, label, 0, 0);
    layout_button(layout, button, 0, 1);
    layout_textview(layout, text, 0, 2);
    layout_hsize(layout, 0, 250);
    layout_vsize(layout, 2, 100);
    layout_margin(layout, 5);
    layout_vmargin(layout, 0, 5);
    layout_vmargin(layout, 1, 5);
    panel_layout(panel, layout);
    return panel;
}

/*---------------------------------------------------------------------------*/

static void i_OnClose(App *app, Event *e)
{
    osapp_finish();
    unref(app);
    unref(e);
}

/*---------------------------------------------------------------------------*/

static App *i_create(void)
{
    App *app = heap_new0(App);
    Panel *panel = i_panel(app);
    app->window = window_create(ekWINDOW_STD);
    app->anim_frame = UINT32_MAX;
    window_panel(app->window, panel);
    window_title(app->window, "Hello, World!");
    window_origin(app->window, v2df(500, 200));
    window_OnClose(app->window, listener(app, i_OnClose, App));
    window_show(app->window);
    return app;
}

/*---------------------------------------------------------------------------*/

static void i_destroy(App **app)
{
    window_destroy(&(*app)->window);
    heap_delete(app, App);
}

/*---------------------------------------------------------------------------*/

static void i_update(App *app, const real64_t prtime, const real64_t ctime)
{
    /* Update animation if is running */
    if (app->anim_frame != UINT32_MAX)
    {
        uint32_t i = 0;
        textview_clear(app->text);
        for (i = 0; i < app->anim_frame; ++i)
            textview_printf(app->text, " ");
        textview_printf(app->text, "=");
        app->anim_frame += 1;

        /* Stops animation in frame 30 */
        if (app->anim_frame == 30)
            app->anim_frame = UINT32_MAX;
    }

    unref(prtime);
    unref(ctime);
}

/*---------------------------------------------------------------------------*/

#include "osmain.h"
osmain_sync(0.04, i_create, i_destroy, i_update, "", App)
```
![animation](https://user-images.githubusercontent.com/42999199/213814333-2b933bb7-414a-49a3-97fa-0988221d06c8.gif)
