### ISSUE TITLE
Accessing mysql/mariadb server

### ISSUE THREAD

**Issue by NejatHakan** [frang75/nappgui_src#41]
I could not figure out how to access my mariadb server with the NAppGUI SDK.

[my actual situation]
I already have installed the required mariadb packages (libmariadb-dev and libssl-dev) for my linux distro (Linux Mint 21.1). Therefore mysql.h is located in "/usr/include/mariadb/mysql.h".

[Enhancement maybe? :-) ]
It would be verry nice if I could for example just edit the main "nappgui_src/src/CMakeLists.txt" file to benefit from your excellent super build pattern.

[final roundup question]
What would be your advice as a best practice if I want my napp gui application let access a mysql/mariadb server?

Thank you in advance,
Best regards Nejat

**Comment by frang75** [comment]
Hi @NejatHakan !

NAppGUI does not have native database support, so you will have to implement it yourself. You can be guided by the Products application, which makes a data connection that comes from http/json. 

https://nappgui.com/en/demo/products.html

In summary, you must:

1) Create the structures in C that can contain the data of your database query.
2) Create the graphical interface (Panel, Window).
3) Connect with dbind the structures to the interface controls.
4) Perform the database query.
5) Map the result of the query to the structures in C.

For your application to compile with mariadb (in `src/CMakeLists.txt`)

```
desktopApp("MyApp" "myapp" "osapp;inet" NRC_PACKED)
target_include_directories("MyApp" PUBLIC "/path/to/mariadb/include")
target_link_libraries("MyApp" "/path/to/mariadb/libmariadb.a(.so)")
```

**Comment by NejatHakan** [comment]
Hi Francisco,

thank your very much for your tips.
I will follow your advice and create a detailed but short documentation and let you know.

**Comment by NejatHakan** [comment]
Hi Francisco,

**VSCode hints 2 error messages concerning 2 lines in src/CMakeLists.txt**

1. CMake Error at CMakeLists.txt:42 (target_include_directories):Cannot specify include directories for target "MyNewApp" which is not built by this project.
2. CMake Error at CMakeLists.txt:43 (target_link_libraries):Cannot specify link libraries for target "MyNewApp" which is not built by this project.

**These are the lines (copy&paste from src/CMakeLists.txt)**
\# Your projects here!
desktopApp("MyNewApp" "myapp" "osapp;inet" NRC_PACKED)
target_include_directories("MyNewApp" PUBLIC "/usr/include/mariadb")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libmariadb.a")

Please take also a closer look in the screenshot if you want to see my VSCode Project structure.


![vscode_cmake_error_hint](https://user-images.githubusercontent.com/8217587/221197250-69157523-a88d-412f-a486-717c71cb2813.png)

**Comment by frang75** [comment]
Hi again! Yes its true, In NAppGUI 1.3 the build system was changed. Put these lines after `generateSoluction()` command.

```
...
generateSolution()

cmake_policy(SET CMP0079 NEW)
target_include_directories("MyNewApp" PUBLIC "/usr/include/mariadb")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libmariadb.a")
```

**Comment by NejatHakan** [comment]
Thanks to the ALLMIGHTY, you can't beliefe how happy I am.
Thanks to the ALLMERCIFULL that I met your project and you.

Yes yes yes it works :-)))))))))

Short backround:
I am a JAVA Developer and started learning C 2 weeks ago.
I don't know how and why but I found your NAppGUI SDK in the world wide web.
And without having expert C knowledge, just by reading your Book (pdf), I realized at once that your C SDK felt so nice and really well designed to me that I decided to learn C by learning your SDK.
I also agree absolutely to the design choices you made, not only concerning the "use of c" chapter but also the design of your Library layers. Because everything makes so sense I could learn to use your SDK to build GUI Apps within 3 days.

Thank you so much making your SDK open source.

Peace be with you and your beloved ones.
Yours Nejat

**Comment by NejatHakan** [comment]
Sorry, I forgot to mention that I had also include following 3 lines.
I really apologize for having this forgotton.

target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libz.so")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libssl.so")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libcrypto.so")

So in overall it looks this now:

\# Your projects here!
desktopApp("MyNewApp" "myapp" "osapp;inet" NRC_PACKED)


generateSolution()

cmake_policy(SET CMP0079 NEW)
target_include_directories("MyNewApp" PUBLIC "/usr/include/mariadb")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libmariadb.a")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libz.so")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libssl.so")
target_link_libraries("MyNewApp" "/usr/lib/x86_64-linux-gnu/libcrypto.so")

Best regards Nejat

**Comment by NejatHakan** [comment]
And here is a bonus for everybody who also wants  to access mariadb.
All the official mariadb  documentation codesnippets only show to use following 2 lines for cleanup:
mysql_free_result(result);
mysql_close(con);

But this is not enough for a correct cleaup.
Valgrind will show warnings that still some bytes are accessible.
Correct way is to also execute "mysql_library_end".
So in code it the correct cleanup should be as follows:

mysql_free_result(result);
mysql_close(con);
mysql_library_end();
