### ISSUE TITLE
TableView scrollbar always visible

### ISSUE THREAD

**Issue by Hummtaro** [frang75/nappgui_src#43]
And here the second issue i got:

The TableView has the vertical scrollbar always visible.
No matter how big the TableView is or how less entries there are, you can scroll one entry down.
And the vertical scrollbar shows before it should, like if you don't let a gap with the same width as the already visible scrollbar..

And as an enhancement it would be nice if the TableView columns could scale automatically to fit the content and if we could specify one or more columns to automatically expand when the windows gets resized.

![Screenshot 2023-02-24 101030](https://user-images.githubusercontent.com/4927294/221146683-8da1d520-7aaf-44a6-8ee7-1919512877ae.png)

**Comment by frang75** [comment]
Hi again @Hummtaro!
I will review this issue ASAP.
Thanks!

**Comment by Hummtaro** [comment]
Thank you!
For now i've just removed the scrollbars :)

**Comment by frang75** [comment]
Fixed in NAppGUI 1.4
