### ISSUE TITLE
nrc (NAppGUI ressource compiler)

### ISSUE THREAD

**Issue by NejatHakan** [frang75/nappgui_src#44]
Hi Francisco,

when cloning your SDK we can find many relevant variations of the nrc executables within the folder "prj/script" for linux, macos and windows.
What is the reason that your SDK ships those executables?
Why are they not compiled during the cmake build process by the available sources?
For me as a "beginner" C Programmer and also beginner "cmake" user it seemed at first that they were maybe compiled by yourself and you maybe just have forgotton to clean them out in your publicly available github project, but then I realized that they are not even overwritten by cmake build process either.

Best regards Nejat

**Comment by frang75** [comment]
Hi @NejatHakan,
 
NRC is required before CMake-Generate because, in projects with resources, some `*.c/*.h` generated by NRC are needed. That's why a precompiled version of NRC is included so it's always available.  However, I plan to change this and compile NRC from the sources before the first CMake-Generate. This forces me to make changes to the build system.

Another user already told me this same case #22. 

I leave this issue open to solve it as soon as possible.

Thanks for the feedback.

**Comment by NejatHakan** [comment]
First of all, I really appreciate how you are responding to all the several issues here. Fast, respectful and full of knowledge from which we all can learn and benefit.

Second: When you have done the nrc binary building from the given sources and stop shipping precompiled executables I can promisse you that "God willing" your really amazing SDK will get ALL THE TRUST it earns.

Thank you so much for taking seriously all of the issues.

Alone the fact that you cross referenced both of the issues shows me a lot how serious person you are.
Meanwhile I will follow your advice in issue number 22.

Do you want me to let this issue here (44) open?

Yours Nejat

**Comment by frang75** [comment]
Hi @NejatHakan!

In next NAppGUI release (1.4), the 'nrc' will be compiled in CMake generate process. All precompiled binaries will be removed.

![image](https://github.com/frang75/nappgui_src/assets/42999199/e36f7110-42ad-4f27-9363-463b4931063e)

**Comment by NejatHakan** [comment]
> Hi @NejatHakan!
> 
> In next NAppGUI release (1.4), the 'nrc' will be compiled in CMake generate process. All precompiled binaries will be removed.
> 
> ![image](https://user-images.githubusercontent.com/42999199/262599598-e36f7110-42ad-4f27-9363-463b4931063e.png)

Hi Francisco,

I am looking forward for your next NAppGUI release (1.4).
Best regrads
Nejat

**Comment by NejatHakan** [comment]
Hi Francisco,

I am looking forward for your next NAppGUI release (1.4).
Best regrads
Nejat

**Comment by frang75** [comment]
Fixed.
NAppGUI 1.4 doesn't include any binary. The nrc is build from sources.
