### ISSUE TITLE
Output unicode (utf8) to console

### ISSUE THREAD

**Issue by Drus566** [frang75/nappgui_src#45]
I try output unicode (utf8) to console like a
```c
const char_t *line = "HI ПРИВЕТ";
String *line_s = str_c(line);
bstd_printf("%s\n", line_s);
// Output
// HI ╨Я╨а╨Ш╨Т╨Х╨в
```

At the same time, everything is fine (unicode utf8 is OK) in the GUI label
![изображение](https://user-images.githubusercontent.com/20108896/234175096-5a044348-d9f2-4c9e-9d80-ba3d9bc94000.png)

How correct out unicode to console?
OS Windows 10. Set chcp 65001 in console

**Comment by Drus566** [comment]
With String is same
```c
const char_t *line = "Привет мир";
Stream *to_stdout = kSTDOUT;
stm_printf(to_stdout, line);
// output
// ╨Я╤А╨╕╨▓╨╡╤В
```

**Comment by frang75** [comment]
Hi @Drus566 ! Thanks for using NAppGUI and the feedback.
Please review these points:
* Your source file is saved as UTF8.
* The font in the console supports Unicode (Console or Lucid Console does).
* chcp 65001 must be set in every session.

* This code is wrong. `bstd_printf` is a wrapper over `printf` %s requires a "C-String" and String is an object.
```
String *line_s = str_c(line);
bstd_printf("%s\n", line_s);
```

```
const char_t *line = "HI ПРИВЕТ";
String *line_s = str_c(line);
bstd_printf("%s\n", line_s);   // Wrong
bstd_printf("HI ПРИВЕТ");   // OK
bstd_printf("%s\n", line);   // OK
bstd_printf("%s\n", tc(line_s));   // OK
str_destroy(&line_s);   // String uses dynamic memory that must be free.
```

```
// This code is OK!
const char_t *line = "Привет мир";
Stream *to_stdout = kSTDOUT;
stm_printf(to_stdout, line);
```
![utf8_1](https://user-images.githubusercontent.com/42999199/234193153-1c417722-923f-450a-95c9-38ad4b16afa1.png)

![utf8_2](https://user-images.githubusercontent.com/42999199/234193181-04b516f1-1a9d-4306-8659-fccde2a1d195.png)

**Comment by Drus566** [comment]
THANK YOU @frang75 ! Yes in console cmd `chcp 65001` is work, but in my windows terminal and powershell need additionally manipulation, i solved this:
```powershell
// open powershell, and open your profile file
vim $PROFILE
// add to profile this string
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
```
Then automatically for this user will set encoding to utf8
