### ISSUE TITLE
How to create and build a single new project instead of re-building the whole package

### ISSUE THREAD

**Issue by LukyGuyLucky** [frang75/nappgui_src#47]
Following the instruction I successfully create my new project and built and ran by running command line "cmake ...." .Great.
However it seems everytime it rebuild the whole package,the libs,the demo apps,the how-to examples,and my small test program.

Is there any plain and simple way to create a new project and then run cmake or vc compiler to just compile and build the specific project(actually just a very small program) I created?

Thanks in advance.

**Comment by frang75** [comment]
Hi @LukyGuyLucky ! Thanks for using NAppGUI and the feedback.

You can remove the sample projects simply by deleting the `/src/demo` and `/src/howto` folders. The `CMakeLists.txt` would look like this:

```
#------------------------------------------
# NAppGUI CMake build script
#------------------------------------------
cmake_minimum_required(VERSION 2.8.12)
project(NAppGUI)

# NAppGUI Build Scripts
get_filename_component(ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR} PATH)
include(${ROOT_PATH}/prj/CMakeNAppGUI.cmake)

# Static libraries
staticLib("sewer" "sewer" "" NRC_NONE)
staticLib("osbs" "osbs" "sewer" NRC_NONE)
staticLib("core" "core" "osbs" NRC_NONE)
staticLib("geom2d" "geom2d" "core" NRC_NONE)
staticLib("draw2d" "draw2d" "geom2d" NRC_NONE)
staticLib("osgui" "osgui" "draw2d" NRC_NONE)
staticLib("gui" "gui" "draw2d" NRC_EMBEDDED)
staticLib("inet" "inet" "core" NRC_NONE)
staticLib("osapp" "osapp" "osgui;gui" NRC_NONE)

# Your projects here!
desktopApp("MyApp" "myapp" "osapp" NRC_EMBEDDED)

generateSolution()
```
On the other hand, it is not necessary to run cmake generate every time you want to recompile the project. It is only needed if you are adding or removing files. If you have only edited the code and want to recompile:

```
cmake --build ./build --config Debug
```
Or `Build Solution` from Visual Studio

**Comment by LukyGuyLucky** [comment]
Thanks for the prompt feedback.

Can I just compile a project by simply running a command scrpt like "gcc -xx -xx blabla " or "mingw32-make -xx -xx blabla" instead of cmake with cmakeList.txt?

**Comment by LukyGuyLucky** [comment]
Thank you for the information regarding BUSY3.

I will stay with cmake .

Just a thinking:A very simple-to-go IDE for NappGUI would help newbies a lot on project management,and also it would be an excellent NappGUI demo for beginners to learn,to modify,to extend the functionality.
