### ISSUE TITLE
Creating a "flyout" window

### ISSUE THREAD

**Issue by MikeLorenz** [frang75/nappgui_src#50]
I'm using the term "flyout" not really knowing if that's the correct word, but what I mean is a window that usually has no borders and can be closed simply by clicking outside the window bounds. Think of the the dropdown list in a ComboBox, for instance, or a popup context menu. Or if you've used a date or time picker, the picker window pops up, but if you don't want to enter anything, you can just click somewhere else and it will go away.

Is this possible to do, given the current start of NAppGUI?

**Comment by frang75** [comment]
Hi @MikeLorenz! Thanks for the feedback.

I'm working in the support for "flyout" windows. It will be ready in next NAppGUI release 1.4.

Keep in contact.

**Comment by frang75** [comment]
Hi @MikeLorenz!
Implementation is almost finish. It will be soon available in GitHub.
![flyout](https://github.com/frang75/nappgui_src/assets/42999199/17336dd5-3b7b-49b1-926c-01de999244f1)

**Comment by MikeLorenz** [comment]
Wow, that looks amazing!!!

**Comment by frang75** [comment]
![flywin_macos](https://github.com/frang75/nappgui_src/assets/42999199/36ff8bef-d0c8-4a44-8993-7d1ddd6d62d6)
![flywin_linux](https://github.com/frang75/nappgui_src/assets/42999199/aa1d304e-4832-4156-8697-8e2003ec88a9)

Now in GitHub: https://github.com/frang75/nappgui_src/commit/ee5c8c8d76b3604151f5d4bbea2e2f405dbfc2ed
