### ISSUE TITLE
Build for MacOS

### ISSUE THREAD

**Issue by chris-deep** [frang75/nappgui_src#53]
Does anyone know how to correct the following?

What I ran >> **cmake -G Xcode -S ./src -B ./build**

Output >>  -- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_C_COMPILER could be found.
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CXX_COMPILER could be found.
-- Configuring incomplete, errors occurred!

How do I setup Xcode / C compiler on MacOS to build the project?  Thanks

**Comment by frang75** [comment]
Hi @chris-deep!

The problem is that CMake can't find your Xcode installation. Please follow these steps.

* Open Xcode if you just installed it. Opening Xcode for the first time finishes installing certain necessary components.
* `sudo xcode-select --reset`
* `xcode-select -p` should return this path: `/Applications/Xcode.app/Contents/Developer`
* Delete any `/build` folder that may have been built inside the `/nappgui_src` directory
* `cd nappgui_src`
* `cmake -G Xcode -S ./src -B ./build`

Regards!

**Comment by chris-deep** [comment]
Ok awesome, will give that a try.  Thanks!

**Comment by chris-deep** [comment]
Great, this worked.  I will check docs on how to build for M1 chip.  The default settings I used built Mac x64 intel binaries.

-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ---------------------------------------------
-- NAppGUI Cross-Platform SDK 1.3.1.4181
-- 2015-2023 Francisco Garcia Collado
-- MIT License
-- ---------------------------------------------
-- Xcode
-- - Clang compiler (14.0.3.14030022)
-- - Xcode: 14.3 SDK: 13.0-Ventura
-- - Deployment Target: 13.0-Ventura
-- - Build architecture: x86_64
-- - Host architecture: arm64
-- - [OK] sewer: Static library
-- - [OK] osbs: Static library
-- - [OK] core: Static library
-- - [OK] geom2d: Static library
-- - [OK] draw2d: Static library
-- - [OK] osgui: Static library
-- - [OK] gui: Static library
-- - [OK] inet: Static library
-- - [OK] osapp: Static library
-- - [OK] casino: Static library
-- - [OK] nrc: Command-line application
-- - [OK] Bode: Desktop application
-- - [OK] Bricks: Desktop application
-- - [OK] Die: Desktop application
-- - [OK] Dice: Desktop application
-- - [OK] Fractals: Desktop application
-- - [OK] HelloWorld: Desktop application
-- - [OK] HelloCpp: Desktop application
-- - [OK] Products: Desktop application
-- - [OK] Col2dHello: Desktop application
-- - [OK] DrawBig: Desktop application
-- - [OK] DrawHello: Desktop application
-- - [OK] DrawImg: Desktop application
-- - [OK] GuiHello: Desktop application
-- - [OK] UrlImg: Desktop application
-- Configuring done (13.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/chris/Work/Dev/napp/nappgui_src/build

**Comment by chris-deep** [comment]
Excellent!  Got it to build M1 binaries, opened in Xcode and built it.  Runs the Drawing Primitives app when I hit Run.  THANKS!

**Comment by frang75** [comment]
Great @chris-deep!

The complete command is:
`cmake -G "Xcode" -S ./src -B ./build -DCMAKE_ARCHITECTURE="arm64"`

More about macOS compilation:
https://nappgui.com/en/guide/win_mac_linux.html#h2

Exactly, by default the x64 version is generated.

Enjoy NAppGUI

**Comment by chris-deep** [comment]
Yep, I read the docs on the site and updated to arm64 build flag.  Worked perfectly!  Just ran some of the demos, stepped through code, etc.  Worked perfectly!!
