### ISSUE TITLE
organize public headers into a single include directory

### ISSUE THREAD

**Issue by stoneface86** [frang75/nappgui_src#54]
First of all, thank you for developing this! I was looking for a lightweight toolkit that I can use instead of Qt and I think I've found it with NAppGUI.

Anyways I'm working on writing some bindings for Nim for this toolkit and I've come across a couple issues doing so with the way the public headers include headers from other libraries.

For example, `draw2d/draw2dall.h` includes `geom2d/geom2dall.h` via a simple `#include "geom2dall.h"`, which is doable because src/geom2d is in the search path when compiling. Using this style of includes makes it hard to install this library in the system (you would have to use a flat directory structure), and also when integrating it in other projects.

I would suggest having all public headers be located in a `include` folder, ie `include/nappgui`, so that this folder alone can be copied into the system's include directory when installing this library. With this, only that include directory needs to be added to the search path when compiling. Private headers can remain where they are.

That way instead of:
```c
#include "geom2dall.h"
```
You would use:
```c
#include "nappgui/geom2d/geom2dall.h"
// or even better:
// #include "nappgui/geom2d.h"
```

This would make things easier when binding to other languages, and being able to use the toolkit as a traditional library would be nice too for package maintainers.

UPDATE: I made a fork and added a [commit](https://github.com/stoneface86/nappgui_src/commit/00480c8a0c722c72b35f1830c6bd957264f0a084) that just adds a copy of all public headers into a top level `include` directory.

**Comment by frang75** [comment]
Hi @stoneface86! Thank you very much for use NAppGUI and for the feedback.

You can group all the public headers of each library with the install command.

```
// Windows
cmake -S ./src -B ./build
cmake --build ./build --config Debug
cmake --install ./build --prefix ./install --config Debug

tree install
Folder PATH listing
Volume serial number is 1AD9-3862
C:\NAPPGUI_SVN\TRUNK\INSTALL
├───bin
│   └───v143_x64
│       └───Debug
│           └───res
├───inc
│   ├───core
│   ├───draw2d
│   ├───geom2d
│   ├───gui
│   ├───inet
│   ├───osapp
│   ├───osbs
│   ├───osgui
│   ├───sewer
│   └───utils
│       └───nlib
└───lib
    └───v143_x64
        └───Debug
``` 
https://nappgui.com/en/guide/build.html#h1

On the other hand, it is not possible to include all the headers in a single directory such as `/nappgui/include` since NAppGUI has not been designed as a monolithic library, but as a set of small independent libraries. Your project can choose which parts of NAppgui it links to.

More info here:
https://nappgui.com/en/guide/build.html#h4

**Comment by stoneface86** [comment]
Ah that install command will be useful. I had wrote a script that copies all the public headers and updates their include directives but using that should make it easier.

I was mostly concerned about naming collisions when using NAppGUI with other libraries. Having the includes grouped under an `nappgui` folder prevents this.

With a path like `nappgui/sewer/blib.h`, you know `blib.h` belongs to NAppGUI's sewer library, as opposed to a plain `blib.h` which tells you nothing and might conflict with another library.

While you say NAppGUI isn't a monolithic library, you still have to link with all libraries (except inet) if you want to use it for its intended purpose, a cross-platform gui toolkit.

**Comment by frang75** [comment]
Your comment is interesting and I will try to improve the use of headers in future releases. 
I leave this issue open. Thanks again for your contribution.

**Comment by frang75** [comment]
Hi @stoneface86 
In NAppGUI 1.4 the headers treatment will change, adding the library folder into #include

```
/* gui.c */
#include "gui.h"
#include "gui.inl"
#include "gbind.inl"
#include "menu.inl"
#include "window.inl"
#include "button.h"
#include "imageview.h"
#include "label.h"
#include "layout.h"
#include "panel.h"
#include "window.h"
#include "res_gui.h"
#include <draw2d/color.h>
#include <draw2d/draw2d.h>
#include <draw2d/guictx.h>
#include <draw2d/font.h>
#include <draw2d/image.h>
#include <geom2d/v2d.h>
#include <core/arrpt.h>
#include <core/arrst.h>
#include <core/event.h>
#include <core/heap.h>
#include <core/hfile.h>
#include <core/hfileh.h>
#include <core/respack.h>
#include <core/respackh.h>
#include <core/strings.h>
#include <osbs/bproc.h>
#include <osbs/bfile.h>
#include <osbs/log.h>
#include <sewer/blib.h>
#include <sewer/bmem.h>
#include <sewer/cassert.h>
#include <sewer/ptr.h>
```

In this way, when library will be installed, will have:

```
├───inc
│   ├───core
│   ├───draw2d
│   ├───geom2d
│   ├───gui
│   ├───inet
│   ├───osapp
│   ├───osbs
│   ├───osgui
│   ├───sewer
│   ├───nappgui.h
```

The final application only will have to point to main include dir `-I your/install/path/nappgui/inc` and `#include <nappgui.h>` for all library headers.

On other way, if you want to include file by file:

```
#include <gui/label.h>
#include <draw2d/draw.h>
#include <core/strings.h>
#include <sewer/cassert.h>

/* Your code here */
```

**Comment by frang75** [comment]
NAppGUI 1.4 install all headers in same root directory.
https://nappgui.com/en/guide/build.html#h3
