### ISSUE TITLE
Documentation: draw_image is missing the image parameter

### ISSUE THREAD

**Issue by stoneface86** [frang75/nappgui_src#57]
I found an error in the documentation, the `draw_image` function is missing documentation on its second parameter, `const Image* image`.

https://nappgui.com/en/draw2d/draw.html#f29

`draw_image_frame` is also missing this parameter as well.

**Comment by frang75** [comment]
Thanks for the report @stoneface86 
I will fix in next documentation review

**Comment by frang75** [comment]
Fixed

https://nappgui.com/en/draw2d/draw.html#f29
https://nappgui.com/en/draw2d/draw.html#f30
