### ISSUE TITLE
Get native handle

### ISSUE THREAD

**Issue by correaelias** [frang75/nappgui_src#58]
Great library, congratulations!
How about adding a function to return the operating system's native identifier (at least for windows, views and panels)?

Something like:
void *get_native_handle(...);

This is useful when using an external graphics library such as BGFX or integrating a game library such as SDL!

**Comment by frang75** [comment]
Hi @correaelias, thanks for the feedback.
You can use the (undocumented) function `view_native(View *view);`

It will return a `HWND`, `GtkWidget` or `NSView` handlers.
