### ISSUE TITLE
blib_strcat help

### ISSUE THREAD

**Issue by millken** [frang75/nappgui_src#61]
test code
```
#include "coreall.h"

int main(int argc, char *argv[])
{
    char_t dest1[5];
    char_t dest2[5];

    blib_strcat(dest1, 5, "hello");
    blib_strcat(dest2, 5, "world");

    log_printf(dest1);
    log_printf(dest2);
    return 0;
}
```
output :
```
[23:44:12] 
[23:44:12] world
```
If I put `log_printf(dest1);` under `blib_strcat(dest1, 5, "hello");`, dest1 outputs "hello" as expected.

**Comment by frang75** [comment]
Your arrays have not been initialized. They contain garbage:
1)
blib_strcpy(dest1, 5, "hello");
blib_strcpy(dest2, 5, "world");
 
2)
dest1[0] = '\0';
dest2[0] = '\0';
blib_strcat(dest1, 5, "hello");
blib_strcat(dest2, 5, "world");

**Comment by millken** [comment]
thanks for your help
