### ISSUE TITLE
Building in Windows enviropment

### ISSUE THREAD

**Issue by alexVertex** [frang75/nappgui_src#73]
Does anyone know how to correct the following?

When I ran >> cmake -S ./src -B ./build

Output >> CMake Error at C:/Users/Alex/Documents/code/nappgui_src/prj/CMakeFunctions.cmake:507 (add_executable):
  No SOURCES given to target: GuiHello
Call Stack (most recent call first):
  C:/Users/Alex/Documents/code/nappgui_src/prj/CMakeFunctions.cmake:785 (processTarget)
  C:/Users/Alex/Documents/code/nappgui_src/prj/CMakeFunctions.cmake:1225 (windowsBundle)
  howto/guihello/CMakeLists.txt:1 (processDesktopApp)

CMake Generate step failed.  Build files cannot be regenerated correctly.
How do I setup Visual Studio or CMAke on Windows to build the project? Thanks

**Comment by frang75** [comment]
Hi @alexVertex 
It seems that the demo project `/howto/guihello` has been deleted from `/src`.

**Comment by alexVertex** [comment]
Thanks, the problem was the cyrillic characters in the path and it's a cmake problem.
