### ISSUE TITLE
Add dynamic creation of window elements/widgets during runtime

### ISSUE THREAD

**Issue by eriklins** [frang75/nappgui_src#74]
I learned that an application window cannot be modified during runtime of an application with NAppGUI. All windows elements/widgets need to be created on app start. However, there exist use-cases where window elements/widgets need to be created during runtime. An example would be my [InsideBlue BLE Tool](https://github.com/eriklins/InsideBlue-BLE-Tool), which does e.g., scan for BLE devices and creates a panel for each discovered BLE device with device specific information. I would consider this as a very useful enhancement of NAppGUI and hope it could get into one of the next feature updates. Would love to use NAppGUI for my next version (actually rewrite) of InsideBlue.

**Comment by frang75** [comment]
Related with
https://github.com/frang75/nappgui_src/issues/18

**Comment by frang75** [comment]
WIP. Alpha version for testing in a separate branch
https://github.com/frang75/nappgui_src/tree/dynlay
![dynlay_full](https://github.com/frang75/nappgui_src/assets/42999199/624a2f9a-c7ff-48d0-97d6-4c3bd501c3da)

**Comment by frang75** [comment]
This feature is implemented in this commit: https://github.com/frang75/nappgui_src/commit/1b6d902b8b3e19ddb185154ae3488a5c6637b02b

Documentation: https://nappgui.com/en/gui/layout.html#h6
