### ISSUE TITLE
Is an offline-copy of the documentation available?

### ISSUE THREAD

**Issue by rochus-keller** [frang75/nappgui_src#8]
E.g. in HTML or PDF format? Not critical, but would be useful.

**Comment by frang75** [comment]
Hi @rochus-keller! 

Yes its possible. I use **ndoc** (my own doc generator) for NAppGUI. It create two outputs.

* HTML: Website format. A webserver is not required. Yo can browse the same web in local. Here you have the entire site. [https://nappgui.com/doc/nappgui_html.zip](https://nappgui.com/doc/nappgui_html.zip). I can mantain this link (1 at month more or less)

* LaTeX/PDF. I don't have this update (but I can do for next version). Here you can download an out-of-date copy. [https://nappgui.com/doc/nappgui_en.pdf](https://nappgui.com/doc/nappgui_en.pdf). **ndoc** offers several eBook posibilities:
     * User Guide format (not Function Reference). 
     * User Guide + Function Reference (at the end of the book).
     * User Guide + Function Reference (mixed in chapters).
     * Full (+ demo applications).

**Comment by rochus-keller** [comment]
Thank you very much; once more impressive work! The PDF is exactly what I was looking for, also a local copy of the navigable HTML API ref is very useful. I'm currently trying to migrate the Bode app to Oberon+ and in parallel extend the language and compiler if need be.

**Comment by frang75** [comment]
@rochus-keller 
I'm still working on creating DLLs and also:
* Make a full review the non-public headers (inl) since I took certain licenses when dealing with static libraries. 
* Upgrade the ebook
* Improve the build system to create user-projects DLLs
* Generate new doc chapter about DLLs

**Comment by frang75** [comment]
PDF Ebook version of documentation has been updated in NAppGUI 1.3

https://nappgui.com/ebook/ndoc_en.pdf
