### ISSUE TITLE
WebView support

### ISSUE THREAD

**Issue by frang75** [frang75/nappgui_src#83]
Incorporate a new control for web browsing.

**Comment by frang75** [comment]
@chris-deep

**Comment by chris-deep** [comment]
Sounds good.  Let me get a plan / design doc together and I'll shoot it to you.

**Comment by frang75** [comment]
W.I.P
![WebView](https://github.com/frang75/nappgui_src/assets/42999199/eeace6fc-2733-41b0-ad84-c238f8759656)

**Comment by chris-deep** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSSSSS

That looks GOOOOOOOD

**Comment by frang75** [comment]
WebView support implemented in this commit: https://github.com/frang75/nappgui_src/commit/586a6a156a222c5a30fa03e41efe782f08e898d2

Doc: https://nappgui.com/en/gui/webview.html
Example: https://nappgui.com/en/howto/webhello.html

**Comment by wxuefei** [comment]
Hi ！
How can I call JavaScript from C++? And how can I call C++ from JavaScript?

**Comment by frang75** [comment]
Hi! At the moment this feature is not implemented in WebView. In future revisions of component may be added.
