### ISSUE TITLE
fseek, ftell?

### ISSUE THREAD

**Issue by rochus-keller** [frang75/nappgui_src#9]
From my point of view it's a very good idea to also include basic features in NAppGUI usually found in the C standard library to avoid compiler/platform dependencies.

But I didn't find fseek nor ftell (or similar functionality), neither in Osbs nor in Core. Can you give me a hint please how I'm supposed to set a file position using NAppGUI?

**Comment by frang75** [comment]
Hi @rochus-keller! nice to read your again!
Indeed, NAppGUI did not provide support for fseek. I just uploaded a commit that implements it.

https://github.com/frang75/nappgui_src/tree/c218c6018946b1a064293bc5e9ebb213c388fcca
https://nappgui.com/en/osbs/bfile.html#f18

Thanks again for your feedback :-)
Keep in touch!

**Comment by rochus-keller** [comment]
Wow, that was fast, thank you.
