### ISSUE TITLE
Any audio snippets or NappGUI (wrapper) implementation

### ISSUE THREAD

**Issue by LukyGuyLucky** [frang75/nappgui_src#91]
Just want to know wheather one has to do in the usual C way to interop with 3rd party audio libraries,or is there a pure NappGUI way to call them like 2D implementation?
Thank you in advance.

**Comment by frang75** [comment]
Hi @LukyGuyLucky. 
No NAppGUI has not native support for audio libraries. You have to link them to your project via CMake or other build system.
