### ISSUE TITLE
Add enable/disable of text-wrap for textview

### ISSUE THREAD

**Issue by eriklins** [frang75/nappgui_src#97]
So far a textview always wraps around the text if the line is exceeding the right edge/border of the textview. Would be great if text-wrap could be disabled, so that the text just exceeds the right edge/border and a horizontal scrollbar get activated.

**Comment by frang75** [comment]
Implemented on this commit: https://nappgui.com/en/gui/textview.html#h4
Doc: https://nappgui.com/en/gui/textview.html#h4

**Comment by eriklins** [comment]
Great, thanks for implementing this!!!
